# SPDX-FileCopyrightText: 2022-present Artur Drogunow <artur.drogunow@zf.com>
#
# SPDX-License-Identifier: MIT */

def time() -> float: ...
def time_ns() -> int: ...
def sleep(secs: float, /) -> None: ...
def sleep_until(t_wakeup_s: float, /) -> None: ...
def sleep_until_ns(t_wakeup_ns: int, /) -> None: ...
def hotloop_until_ns(t_wakeup_ns: int, /) -> None: ...
