# SPDX-FileCopyrightText: 2022-present Artur Drogunow <artur.drogunow@zf.com>
#
# SPDX-License-Identifier: MIT */

from typing import Callable

def time() -> float: ...
def time_ns() -> int: ...
def sleep(timeout: float, /) -> None: ...
def _sleep_until(t_wakeup_s: float, /) -> None: ...
def _sleep_until_ns(t_wakeup_ns: int, /) -> None: ...
def _hotloop_until_ns(t_wakeup_ns: int, /) -> None: ...
